Repository vite-ma-planete/vite-ma-planete, pull requests merged in 2023-12, with the labels that each got.

#3 feat: setup mui and carbon
  apps/www/postcss.config.js
  apps/www/src/app/[locale]/global.css
  apps/www/src/app/[locale]/graphs/page.tsx
  apps/www/src/app/[locale]/layout.tsx
  apps/www/src/app/[locale]/page.tsx
  apps/www/src/lib/theme.light.ts
  apps/www/tailwind.config.js
  package.json
  packages/ui/src/index.ts
  packages/ui/src/lib/Loader.tsx
  packages/ui/src/lib/ui.module.css
  packages/ui/src/lib/ui.spec.tsx
  packages/ui/src/lib/ui.tsx
  pnpm-lock.yaml
Labels: enhancement, type: feature, version: minor

#7 fix: temporary fix for header nav
  packages/i18n/src/lib/i18n.tsx
  packages/ui/src/lib/Header.tsx
Labels: type: bug, version: patch

#6 feat: add questions page
  apps/www/src/app/graphs/page.tsx
  apps/www/src/app/page.tsx
  apps/www/src/app/questions/page.tsx
  package.json
  packages/i18n/src/lib/translations/en.json
  packages/i18n/src/lib/translations/fr.json
  packages/ui/src/lib/Header.tsx
  packages/ui/src/lib/QuestionAccordion.tsx
  yarn.lock
Labels: type: feature, version: minor

#10 feat: add associations page
  apps/www/public/350.org.jpg
  apps/www/public/act_for_the_environment.jpg
  apps/www/public/alternatiba.jpg
  apps/www/public/french_federation_of_bicycle_users.jpg
  apps/www/public/student_network_for_an_ecological_and_solidarity_society.jpg
  apps/www/src/app/associations/page.tsx
  packages/i18n/src/lib/translations/en.json
  packages/i18n/src/lib/translations/fr.json
  packages/ui/src/lib/AssociationCard.tsx
Labels: type: feature, version: minor

#12 feat: chatbot production url
  packages/ui/src/lib/chatbot/Chatbot.tsx
Labels: type: feature, version: minor
